[package]
name = "r2d2_postgres"
version = "0.11.1"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT"
description = "Postgres support for the r2d2 connection pool"
repository = "https://github.com/sfackler/r2d2-postgres"
documentation = "https://sfackler.github.io/r2d2-postgres/doc/v0.11.1/r2d2_postgres"
keywords = ["postgres", "sql", "pool", "database"]

[lib]
name = "r2d2_postgres"
path = "src/lib.rs"
test = false

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies]
r2d2 = ">= 0.6, < 0.8"
postgres = ">= 0.12, < 0.15"
