[package]
name = "r2d2_postgres"
version = "0.0.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[[lib]]
name = "r2d2_postgres"
path = "src/lib.rs"
test = false

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies.rust-postgres]
git = "https://github.com/sfackler/rust-postgres"
rev = "ab59eac6fc076f35f7a2a542e5a10cc94211a9b6"

[dependencies.r2d2]
git = "https://github.com/sfackler/r2d2"
rev = "4a087cf21097459a5107bf7152424e09483314be"
