[package]
name = "r2d2_postgres"
version = "0.0.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[lib]
name = "r2d2_postgres"
path = "src/lib.rs"
test = false

[[test]]
name = "test"
path = "tests/test.rs"

[dependencies.postgres]
git = "https://github.com/sfackler/rust-postgres"

[dependencies.r2d2]
git = "https://github.com/sfackler/r2d2"
rev = "28c28642e643bbf8275ee4ef641eef2b8f53a88f"
